### PR TITLE
Nartin9 patch 1

### PR DESCRIPTION
**Pull request by nartin9**
Finished test class for randomGenerator

### CODE REVIEW

**Comment by dv258** [comment]
The Travis CI tests failed. Can you fix the issues and make a new pull request?

**Comment by nartin9** [comment]
fixed randomgenerator.py

**Comment by nartin9** [comment]
once I get home I will test the randomgenerator.py class to make sure they is nothing less wrong other than syntax

**Comment by dv258** [comment]
There are still syntax issues and the methods should be static methods in the class. Please fix it and make sure the tests pass

**Pull request closed without merging**
